/**
 * generated by Xtext
 */
package monoge.dsl.validation;

import monoge.dsl.validation.AbstractExtensionValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ExtensionValidator extends AbstractExtensionValidator {
}
