/*
 * generated by Xtext 2.13.0
 */
package org.atlanmod.emfviews.mel.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MelUiModule extends AbstractMelUiModule {
}
