/*
* generated by Xtext
*/
package emfviews.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class VpdlUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return emfviews.dsl.ui.internal.VpdlActivator.getInstance().getInjector("emfviews.dsl.Vpdl");
	}
	
}
