/*
 * generated by Xtext 2.12.0
 */
package fr.inria.atlanmod.emfviews.vpdl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class VpdlStandaloneSetup extends VpdlStandaloneSetupGenerated {

	def static void doSetup() {
		new VpdlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
