/*
 * generated by Xtext 2.12.0
 */
package fr.inria.atlanmod.emfviews.vpdl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class VpdlRuntimeModule extends AbstractVpdlRuntimeModule {
}
