sudo: false
language: java
jdk: openjdk8

services:
- docker

install:
  - git clone --depth 1 https://github.com/atlanmod/sexp2emf.git
  - mvn --batch-mode -Dmaven.javadoc.skip=true --file sexp2emf/pom.xml install

script:
  # Build the manual before mvn, because this also populates the emfviews.doc
  # plugin.
  # Pull a docker image with Emacs and Cask for convenience.
  - docker run --volume "$TRAVIS_BUILD_DIR"/doc:/emfviews-doc
               --workdir /emfviews-doc
               flycheck/emacs-cask:26.1
               /bin/bash -c "cask install && make"

  # Then build and test all Java plugins
  - mvn --show-version --batch-mode -Dmaven.javadoc.skip=true -P update-site verify

# The deploy stage runs only for the master branch and tags, only if the build
# succeeded, and never for pull requests.
deploy:
  - provider: script
    skip_cleanup: true
    script: bash .travis/deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash .travis/deploy.sh
    on:
      tags: true
