/*
 * generated by Xtext
 */
package emfviews.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import emfviews.dsl.ui.internal.SqlviewActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SqlviewExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SqlviewActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SqlviewActivator.getInstance().getInjector(SqlviewActivator.EMFVIEWS_DSL_SQLVIEW);
	}
	
}
