<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="virtuallinks" nsURI="http://inria.fr/virtualLinks" nsPrefix="virtualLinks">
  <eClassifiers xsi:type="ecore:EClass" name="WeavingModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="virtualLinks" upperBound="-1"
        eType="#//VirtualLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributingModels" upperBound="-1"
        eType="#//ContributingModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="whitelist" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="virtualConcepts" upperBound="-1"
        eType="#//VirtualConcept" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="virtualProperties" upperBound="-1"
        eType="#//VirtualProperty" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="virtualAssociations" upperBound="-1"
        eType="#//VirtualAssociation" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="virtualElements" upperBound="-1"
        eType="#//VirtualElement" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1"
        eType="#//Filter" changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualLink" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualConcept" eSuperTypes="#//VirtualLink #//VirtualElement #//Concept">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superConcepts" upperBound="-1"
        eType="#//Concept"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subConcepts" upperBound="-1"
        eType="#//Concept"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualProperty" eSuperTypes="#//VirtualLink #//VirtualElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//Concept"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualAssociation" eSuperTypes="#//VirtualLink #//VirtualElement #//Association">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Concept"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Concept"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" ordered="false"
        eType="#//Association"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="composition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Filter" eSuperTypes="#//VirtualLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ConcreteElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContributingModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URI" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concreteElements" upperBound="-1"
        eType="#//ConcreteElement" containment="true" eOpposite="#//ConcreteElement/model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//ContributingModel"
        eOpposite="#//ContributingModel/concreteElements"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concept" abstract="true" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="Association" abstract="true" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteConcept" eSuperTypes="#//ConcreteElement #//Concept"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteAssociation" eSuperTypes="#//ConcreteElement #//Association"/>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualElement" abstract="true" eSuperTypes="#//Element"/>
</ecore:EPackage>
