/*
 * generated by Xtext 2.12.0
 */
package org.atlanmod.emfviews.vpdl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class VpdlStandaloneSetup extends VpdlStandaloneSetupGenerated {

	def static void doSetup() {
		new VpdlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
