/*
 * generated by Xtext
 */
package emfviews.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VpdlUiModule extends emfviews.dsl.ui.AbstractVpdlUiModule {
	public VpdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
