/*
 * generated by Xtext
 */
package emfviews.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import emfviews.dsl.ui.internal.VpdlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VpdlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return VpdlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return VpdlActivator.getInstance().getInjector(VpdlActivator.EMFVIEWS_DSL_VPDL);
	}
	
}
