/*
 * generated by Xtext 2.12.0
 */
package org.atlanmod.emfviews.vpdl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class VpdlUiModule extends AbstractVpdlUiModule {
}
