// Definition of my extension  
       
import uml from 'http://www.eclipse.org/uml2/5.0.0/UML' 
import bpmn from 'http://www.omg.org/spec/BPMN/20100524/MODEL-XMI'
          
define extension1 extending uml, bpmn {    
	add class X
	add class Y specializing uml.Class, uml.Abstraction
	add class Z supertyping uml.Activity, uml.Action, X 
	add class B specializing Y supertyping Z 
	   
	modify class Z { 
		add property foo : EString 0
	}   
 
	modify class uml.Class {
		add property opt : EString 0
		add property nonOpt : EString 1
		add composition refC : Y 0..*
		add association ref : uml.Action 1..*
		add constraint constraint1 "one e1" 
	}
	   
	modify class bpmn.Activity { 
		modify association default {
			name defaultRenamed 
			type X 
			cardinality 0..*
			relation-type association
		}
		filter constraint constraint2
	}  
	
	modify class uml.Behavior {
		modify property isReentrant {
			type EString  
			//cardinality 0
		} 
		//filter property isReentrant
	}
	
	modify class uml.Activity {
		modify property isReadOnly {
			type EBoolean 
			cardinality 0 
		}
	}
	 
	filter class uml.DataType 
}
