/*
* generated by Xtext
*/
package monoge.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ExtensionStandaloneSetup extends ExtensionStandaloneSetupGenerated{

	public static void doSetup() {
		new ExtensionStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

