/*
 * generated by Xtext
 */
package monoge.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExtensionRuntimeModule extends monoge.dsl.AbstractExtensionRuntimeModule {

}
