/*
 * generated by Xtext 2.13.0
 */
package org.atlanmod.emfviews.mel.ide

import com.google.inject.Guice
import org.atlanmod.emfviews.mel.MelRuntimeModule
import org.atlanmod.emfviews.mel.MelStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MelIdeSetup extends MelStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MelRuntimeModule, new MelIdeModule))
	}

}
