/*
* generated by Xtext
*/
package emfviews.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import emfviews.dsl.services.VpdlGrammarAccess;

public class VpdlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private VpdlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected emfviews.dsl.parser.antlr.internal.InternalVpdlParser createParser(XtextTokenStream stream) {
		return new emfviews.dsl.parser.antlr.internal.InternalVpdlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public VpdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(VpdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
