/**
 * generated by Xtext
 */
package emfviews.dsl.validation;

import emfviews.dsl.validation.AbstractVpdlValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class VpdlValidator extends AbstractVpdlValidator {
}
