/**
 * generated by Xtext
 */
package emfviews.dsl.ui.contentassist;

import emfviews.dsl.ui.contentassist.AbstractSqlviewProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SqlviewProposalProvider extends AbstractSqlviewProposalProvider {
}
