/*
* generated by Xtext
*/
package emfviews.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class VpdlStandaloneSetup extends VpdlStandaloneSetupGenerated{

	public static void doSetup() {
		new VpdlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

