/*
 * generated by Xtext 2.12.0
 */
package org.atlanmod.emfviews.mel


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MelStandaloneSetup extends MelStandaloneSetupGenerated {

	def static void doSetup() {
		new MelStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
