/*
* generated by Xtext
*/
package monoge.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import monoge.dsl.services.ExtensionGrammarAccess;

public class ExtensionParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ExtensionGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected monoge.dsl.parser.antlr.internal.InternalExtensionParser createParser(XtextTokenStream stream) {
		return new monoge.dsl.parser.antlr.internal.InternalExtensionParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public ExtensionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ExtensionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
