/*
 * generated by Xtext 2.12.0
 */
package fr.inria.atlanmod.emfviews.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MelUiModule extends AbstractMelUiModule {
}
