/*
 * generated by Xtext
 */
package emfviews.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SqlviewRuntimeModule extends emfviews.dsl.AbstractSqlviewRuntimeModule {

}
