/*
* generated by Xtext
*/
package emfviews.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SqlviewStandaloneSetup extends SqlviewStandaloneSetupGenerated{

	public static void doSetup() {
		new SqlviewStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

