/*
 * generated by Xtext
 */
package emfviews.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSqlviewValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(emfviews.dsl.sqlview.SqlviewPackage.eINSTANCE);
		return result;
	}
}
