/*
* generated by Xtext
*/
package emfviews.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import emfviews.dsl.services.SqlviewGrammarAccess;

public class SqlviewParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SqlviewGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected emfviews.dsl.parser.antlr.internal.InternalSqlviewParser createParser(XtextTokenStream stream) {
		return new emfviews.dsl.parser.antlr.internal.InternalSqlviewParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public SqlviewGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SqlviewGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
