/*
 * generated by Xtext
 */
package monoge.dsl.ui.contentassist

import monoge.dsl.ui.contentassist.AbstractExtensionProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ExtensionProposalProvider extends AbstractExtensionProposalProvider {
}
